import { FYERS_OPTION_INDEX_SYMBOLS } from './fyers-symbols.js';
import { TIMELINE_DEFAULTS } from './technical-analysis.js';
import { TradingStyle } from '../types/trading-style.js';

export const SESSION_DEFAULTS = {
  IST_TIMEZONE: TIMELINE_DEFAULTS.IST_TIMEZONE,
  SESSION_OPEN: TIMELINE_DEFAULTS.SESSION_OPEN,
  SESSION_CLOSE: TIMELINE_DEFAULTS.SESSION_CLOSE,
  DEFAULT_SYMBOLS: [FYERS_OPTION_INDEX_SYMBOLS[0].symbol],
  DEFAULT_TRADING_STYLES: [TradingStyle.Intraday],
  SIGNAL_EXIT_CONFIRM_POLLS: 3,
  SIGNAL_OPPOSITE_CONFIRM_POLLS: 2,
  SIGNAL_EXIT_CONVICTION_RATIO: 0.7,
  SIGNAL_EXIT_CONVICTION_FLOOR_MIN: 35,
} as const;
