import { FYERS_OPTION_INDEX_SYMBOLS } from './fyers-symbols.js';
import { TIMELINE_DEFAULTS } from './technical-analysis.js';
import { TradingStyle } from '../types/trading-style.js';

export const TELEGRAM_NOTIFICATION_DEFAULTS = {
  COLLECTION: 'signal-snapshots',
  SESSION_STATE_COLLECTION: 'telegram-session-state',
  POLL_INTERVAL_MS: 60 * 1000,
  IST_TIMEZONE: TIMELINE_DEFAULTS.IST_TIMEZONE,
  SESSION_OPEN: TIMELINE_DEFAULTS.SESSION_OPEN,
  SESSION_CLOSE: TIMELINE_DEFAULTS.SESSION_CLOSE,
  POST_SESSION_COACH_WINDOW_MINUTES: 45,
  LEARNING_LOOKBACK_DAYS: 10,
  PRE_SESSION_LEARNING_START: { hour: 9, minute: 0 },
  PRE_SESSION_LEARNING_END: { hour: 9, minute: 20 },
  DEFAULT_SYMBOLS: [FYERS_OPTION_INDEX_SYMBOLS[0].symbol],
  DEFAULT_TRADING_STYLES: [TradingStyle.Intraday],
  MIN_CONVICTION_FOR_INITIAL_ALERT: 35,
  SIGNAL_ENTRY_CONFIRM_POLLS: 2,
  SIGNAL_EXIT_CONFIRM_POLLS: 3,
  SIGNAL_OPPOSITE_CONFIRM_POLLS: 2,
  SIGNAL_EXIT_CONVICTION_RATIO: 0.7,
  SIGNAL_EXIT_CONVICTION_FLOOR_MIN: 35,
  TP_SNAPSHOT_COLLECTION: 'position-tp-snapshots',
  ENTRY_INTENT_COLLECTION: 'trade-entry-intents',
  ALERT_WHY_CONTEXT_COLLECTION: 'alert-why-context',
  SIGNAL_OUTCOMES_COLLECTION: 'signal-outcomes',
  SIGNAL_OUTCOME_RETENTION_DAYS: 90,
  COMMAND_POLL_LONG_TIMEOUT_SEC: 25,
  COMMAND_POLL_INTERVAL_MS: 2 * 1000,
  ENTRY_INTENT_WINDOW_MS: 3 * 60 * 60 * 1000,
  TP_APPROACH_WITHIN_R: 0.3,
  TP_APPROACH_MIN_POINTS: 8,
} as const;

export const TELEGRAM_API_BASE = 'https://api.telegram.org';